###############################################################################
#                          WDEV   WASHINGTON                                  #
###############################################################################
version: '3.1'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx-chess
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "${NGINX_PORT}:${NGINX_PORT}"
        env_file:
            - ".env"
        command: /bin/sh -c "export NGINXPROXY && envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
